module.exports = [
  {
    "itemName": "branch",
    "description": "a dry, brown branch",
    "category": "nature",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "mushroom",
    "description": "a small, white mushroom with a round top",
    "category": "nature",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "sock",
    "description": "a lone argyle sock, blue and yellow",
    "category": "household",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [
      "feetSlot"
    ],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "pumpkin pie",
    "description": "a whole pumpkin pie! It smells like autumn",
    "category": "food",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "collar",
    "description": "A red collar with a silver buckle. It has pictures of fish on it",
    "category": "clothing",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [
      "neckSlot"
    ],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "leather gloves",
    "description": "nice leather gloves. They look protective.",
    "category": "armor",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "collar",
    "description": "A red collar with a silver buckle. It has pictures of fish on it",
    "category": "clothing",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "blue shirt",
    "description": "a simple blue linen shirt, good for warm weather",
    "category": "clothing",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [
      "torsoSlot"
    ],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "fancy shirt",
    "description": "a fancy white linen shirt with detail in many colors along all the edges",
    "category": "clothing",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [
      "torsoSlot"
    ],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "pair of brown pants",
    "description": "a pair of simple brown linen pants, excellent for warm weather",
    "category": "clothing",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [
      "legsSlot"
    ],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "pair of fancy slacks",
    "description": "a pair of fancy pressed black slacks, made of fine wool",
    "category": "clothing",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [
      "legsSlot"
    ],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "pair of green socks",
    "description": "a pair of green cotton socks",
    "category": "clothing",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [
      "feetSlot"
    ],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "ball",
    "description": "a simple cloth ball filled with sand",
    "category": "tools",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "dull ring",
    "description": "a dull metal ring with signs of many years of wear",
    "category": "tools",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "flower",
    "description": "a a pretty little wildflower",
    "category": "nature",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "acorn",
    "description": "a small brown nut with a jaunty cap",
    "category": "nature",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "toadstool",
    "description": "an alarmingly bright red mushroom with white spots",
    "category": "nature",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "mushroom patch",
    "description": "a smallish patch of white, round mushrooms",
    "category": "nature",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "strawberry patch",
    "description": "a little patch of green leaves with red berries peeking out from underneath",
    "category": "nature",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "hazelnut bush",
    "description": "a group of strong shoots with fuzzy, pointed leaves, and sets of prickly hazelnuts",
    "category": "nature",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "huckleberry bush",
    "description": "a delicate bush with neat little leaves and tiny, round, red berries",
    "category": "nature",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "blackberry bush",
    "description": "a wicked looking bush with razor sharp thorns glinting evilly at you. Oh, and some berries",
    "category": "nature",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "button",
    "description": "a small, round button with two hole",
    "category": "household",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "vein of iron",
    "description": "an outcropping of rock with a bit of iron ore showing through",
    "category": "mountains",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "vein of tin",
    "description": "an outcropping of rock with a bit of tin ore showing through",
    "category": "mountains",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "vein of copper",
    "description": "an outcropping of rock with a bit of copper ore showing through",
    "category": "mountains",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "vein of zinc",
    "description": "an outcropping of rock with a bit of zinc ore showing through",
    "category": "mountains",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "plum tree",
    "description": "a medium sized tree with ripe, purple plums hanging off of it",
    "category": "mountains",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "apple tree",
    "description": "a medium sized tree with round, shiny, red and yellow apples glinting from the branches",
    "category": "nature",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  },
  {
    "itemName": "dagger",
    "description": "a small steel dagger with a leather wrapped handle",
    "category": "weapon",
    "inventorySize": 0,
    "edible": false,
    "healthEffect": 0,
    "equippable": [
      "rightHandSlot",
      "leftHandSlot"
    ],
    "dexterityEffect": 0,
    "strengthEffect": 0,
    "wisdomEffect": 0,
    "xpEffect": 0
  }
]